Fix to issue 299 and 297
nf-core/scrnaseq pull request #300
Opened 2024-02-02 11:42 UTC by heylf

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/scrnaseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/scrnaseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-02-02 11:43 UTC, heylf commented
This PR should fix the issues [297](https://github.com/nf-core/scrnaseq/issues/297) and [299](https://github.com/nf-core/scrnaseq/issues/299)

2024-02-02 11:58 UTC, grst requested changes

2024-02-02 11:58 UTC, grst commented on modules/local/mtx_to_seurat.nf
> +        features = "filtered_feature_bc_matrix/features.tsv.gz"
This breaks the cellranger workflow. It seems one of the modules outputs these files in a subfolder, while the other does not.

2024-02-14 10:37 UTC, grst commented
Now that @fmalmeida set-up nf-test, it would be great to add a testcase for cellranger-arc to make sure such issues don't arise again.

2024-02-15 09:53 UTC, heylf commented
> Now that @fmalmeida set-up nf-test, it would be great to add a testcase for cellranger-arc to make sure such issues don't arise again.

I agree. I assigned myself to that issue. I will do it latest before the March Hackathon.

2024-03-07 11:43 UTC, grst commented
@heylf, could you please take another look? I'm afraid something got screwed up by merging in the template update.

2024-03-07 16:19 UTC, heylf commented
@grst yeah saw right now that this PR was still hanging https://github.com/nf-core/modules/pull/4839. If its merged then it should be fine.

2024-03-11 14:26 UTC, grst commented
@heylf, if you look at the diff, there's now basically no changes left since I merged in the template update.

2024-03-11 17:27 UTC, heylf commented
@grst Yeah its fine to merge

2024-03-13 07:07 UTC, grst approved these changes
LGTM

2024-03-13 07:18 UTC, merged