PR for 1.1.0 release
nf-core/scrnaseq pull request #52
Opened 2021-03-24 14:48 UTC by apeltzer

Many thanks to contributing to nf-core/scrnaseq!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/scrnaseq branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/scrnaseq)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/scrnaseq/tree/master/.github/CONTRIBUTING.md

2021-03-24 15:02 UTC, apeltzer commented
Yeah the failing nf-core lint on release is something that has been fixed in 1.13.3 which is due for release in like 15min? @KevinMenden no?

2021-03-24 15:06 UTC, ggabernet commented
oh noooo another tools release...

2021-03-24 21:18 UTC, ggabernet requested changes

2021-03-24 21:18 UTC, ggabernet commented on conf/test_full.config
> +  // TODO nf-core: Specify the paths to your full test data ( on nf-core/test-datasets or directly in repositories, e.g. SRA)
It would be great to find real sized test data, but I guess we can also leave it for the DSL2 release if we just wanna get this code out now

2021-03-24 21:18 UTC, ggabernet commented on docs/usage.md
All of the parameter docs should be removed as they will be parsed from the json schema to the website

2021-03-24 21:19 UTC, ggabernet commented
All looks good to me, except there is still the documentation on the parameters that it's not needed any more, and should be removed as it is parsed from the json file now

2021-03-25 09:00 UTC, apeltzer commented
@sk-sahu you want to remove the parameter docs then?

2021-03-29 07:51 UTC, merged